### ISSUE TITLE
Wider range for cycle

### ISSUE THREAD

**Issue by silverhook** [amilcarsantos/harbour-sailgirlz#1]
According to [Wikipedia](https://en.wikipedia.org/wiki/Menstrual_cycle) a typical menstrual cycle lasts between 21 and 45 days.

You might want to change the minimal and maximal allowed values for `cycleLength` accordingly (and maybe widen it up a bit more as well to include atypical occurrences).

**Comment by amilcarsantos** [comment]
I've based the interval from the site maemequer.pt, but no issue in widening the range...

**Comment by silverhook** [comment]
Cool, thanks :+1:

**Comment by amilcarsantos** [comment]
Done in release v0.2
